### PR TITLE
Update Travis

### PR DESCRIPTION
**Pull request by ssayer**
Move to new travis "trusty tahr" environement and update dependencies

### CODE REVIEW

**Comment by rbclark** [comment]
It looks like using the phantomJS version that comes with with trusty is still a bit old, it will probably still work better if we use 2.1.1 directly.

**Comment by ssayer** [comment]
Are we still getting that weird Mongo JS loading failure?

**Comment by rbclark** [comment]
Yeah unfortunately those errors are still popping up. Do you know what version of mongo the trusty beta is running? I believe we are planning to target 3.4 for the next release, is that the version they are running or do we need to add the 3.4 apt sources?

**Comment by ssayer** [comment]
I don't. The old travis image used 3.2, which necessitated us downgrading to 3.0. It look like this passed so I would assume it's using 3.4?

**Comment by rbclark** [comment]
It looks like it is running on 3.2 still, I actually had a PR in before to bump to 3.4 #800 and it got merged and somehow reverted.

**Comment by okeefm** [comment]
#800 was merged into `cypress_3_2`, not master, so we're still building on master with 3.0

**Comment by rbclark** [comment]
Oh in that case this is gonna cause a bit of merge conflict for the person merging 3.2, perhaps this should be put against cypress_3.2?

**Comment by ssayer** [comment]
Changed base to 3.2. I mostly did this as an experiment, but if you want this merged this into 3.2, go ahead and deconflict.

**Comment by rbclark** [comment]
`Scenario: Can Multi Upload to the Same Task on a Measure Test Multiple Times` is having intermittent failures again as a result of this PR, it could be the new container infrastructure is a lot slower to run than the old travis which is causing it to timeout. If we merge this in I worry we will start to get a lot of intermittent test failures again. There will probably need to be some investigation into why exactly this has popped back up.

**Comment by rbclark** [comment]
Small followup on the previous error, it seems that the random failures may be happening due to the trusty container infrastructure running significantly slower, the old jobs seem to take between 17-20 minutes on precise but take 33-36 minutes on trusty. I'm going to look into bumping the timeout to see if that helps. Also going to look into whether the page still has a pending refresh based on the html output of this failing test.

**Comment by rbclark** [comment]
Sorry for hijacking this PR, unfortunately the issue is made much worse by this version of travis so testing on this branch is the most convenient place to do so. I have tried a few changes and I hope they help improve the reliability.

**Comment by ssayer** [comment]
No problem, I just wanted to do a few experiments (some of which failed, like switching from poltergeist to webkit). If it's being useful, I'm glad it's living on!

**Comment by rbclark** [comment]
I believe the multi upload is stable at this point. Unfortunately other tests are still intermittently failing, perhaps simply due to how slow it seems our tests our running on the trusty beta. I would suggest we hold off on merging this until we have more information about why they are running so badly, I have sent an email to travis support to see if they have any input.

**Comment by rbclark** [comment]
I have moved all of the fixes for this PR in to a new pull request specific to those fixes instead of them being tied in with the travis update.

**Pull request closed without merging**
