### PR TITLE
validate qrda templates. error if C3, warning if not C3

### PR DESCRIPTION
**Pull request by dczulada**
This will fail.  Needs the updated HDS

### CODE REVIEW

**Comment by okeefm** [comment]
Is this good to get reviewed? Looks like it's passing Travis now, so I assume the required HDS has been merged in.

**Comment by okeefm** [comment]
@dczulada: this PR has conflicts that needs to be resolved.

**Comment by dczulada** [comment]
@okeefm conflicts have been resolved

**Comment by okeefm** [comment]
Now Travis is failing :(

**Pull request merged**
