### PR TITLE
Add browser tests

### PR DESCRIPTION
**Pull request by thecristen**
(Hoping the new updates help).

Surprise!

With this change you can run your Cucumber tests in a browser. This can be helpful in trying to understand what on earth your test is actually doing.

For example,
```
IN_BROWSER=true PAUSE=1 bundle exec cucumber -n "Successful Create Vendor"
```
The `PAUSE` adds time between the steps.

### CODE REVIEW

**Comment by okeefm** [comment]
Is this going to break things because we're switching HDS/QME branches? If so, can we merge the changes in `bump_rubyzip` into `bump_mongoid` on the respective gems?

**Comment by thecristen** [comment]
Merging those sounds like a good option. Could you arrange that @okeefm ?

**Comment by okeefm** [comment]
@thecristen done; If you point this branch at the latest HDS/QME `bump_mongoid` commits, you should have the correct version of Rubyzip.

**Comment by okeefm** [comment]
Looks like you have to run a `bundle update` to get the latest HDS/QME versions on this branch.

**Comment by okeefm** [comment]
Looks good to me. Only note: the `no_proxy` environment variable needs to include `127.0.0.1`, and you need to have Firefox installed, for this to work.

**Comment by okeefm** [comment]
This branch has merge conflicts now :(

**Comment by thecristen** [comment]
No conflicts anymore :)

**Pull request merged**
