### PR TITLE
strat should be in its own row

### PR DESCRIPTION
**Pull request by dczulada**

### CODE REVIEW

**Comment by tstrass** [comment]
@dczulada would you mind just posting a screenshot? I tried to make an example but I don't know how to cause reporting errors.

**Comment by dczulada** [comment]
screen shot 2016-09-28 at 9 24 39 am

**Comment by tstrass** [comment]
I know this isn't something new with this PR, but is there a reason we have reporting errors grouped into different tables, and if so should there be some kind of indication of what the groupings mean?

**Comment by dczulada** [comment]
Yes they should be grouped

screen shot 2016-09-28 at 11 26 50 am

screen shot 2016-09-28 at 11 27 20 am

**Pull request merged**
