### PR TITLE
all product_tests can have duplicate records

### PR DESCRIPTION
**Pull request by dczulada**

### CODE REVIEW

**Comment by okeefm** [comment]
Is it that all "`ProductTest`s _will_ have duplicate records", or "all `ProductTest`s _can_ have duplicate records"?

**Comment by dczulada** [comment]
its the second.  bad commit message

**Comment by okeefm** [comment]
Though on second thought this should be coordinated with @lmd59 to make sure it doesn't break her test creation random seed PR (#757)

**Comment by okeefm** [comment]
Going to have to rebase this (and resolve conflicts) because I pulled in #757

**Pull request merged**
