### PR TITLE
Added supplement test artifact upload

### PR DESCRIPTION
**Pull request by rbclark**
This PR adds the ability for ATLs to upload a custom "Supplemental Test Artifact" which can be downloaded from the product page by all other ATLs and admin.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] Internal ticket for this PR: https://jira.mitre.org/browse/CYPRESS-140
- [x] Internal ticket links to this PR
- [x] Code diff has been done and been reviewed
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass

**Reviewer 1:**

Name: @okeefm
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

**Reviewer 2:**

Name: @laclark22
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

### CODE REVIEW

**Comment by rbclark** [comment]
Not sure why the code coverage is showing such a drop here, there are cucumber tests covering each method it is claiming are failing.

**Comment by okeefm** [comment]
Does Codecov take Cucumber tests into account?

**Comment by okeefm** [comment]
Also, I would suggest allowing `.pdf` as a format if we're restricting filetypes.

**Comment by okeefm** [comment]
And maybe `.zip`? @dczulada what's your thought?

**Pull request merged**
